# Data Preprocessing

In [73]:
telco_data["Churn"] = telco_data["Churn"].map({"Yes": 1, "No": 0})

In [74]:
telco_data['SeniorCitizen'] = telco_data['SeniorCitizen'].map({"Yes": 1, "No": 0})

In [82]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data1 = telco_data.copy()

data1[categorical_cols] = data1[categorical_cols].apply(le.fit_transform)
data1[['Churn']] = data1[['Churn']].apply(le.fit_transform)

In [83]:
data1.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1

Splitting into train and test sets

In [86]:
from sklearn.model_selection import train_test_split

X = data1.drop(columns=['Churn'],axis=1)
y = data1['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 23)

Feature Scaling

In [87]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
categorical_scaled = std_scaler.fit_transform(data1)